### ISSUE TITLE
session

### ISSUE THREAD

**Issue by quasiperfect** [avenirer/CodeIgniter-Postal#2]
hi 

why would you load codeigniter's session and then use $_SESSION ?

**Comment by avenirer** [comment]
Hello. Because starting CI3, we are using $_SESSION. And this library was made for CI3 :) https://codeigniter.com/user_guide/libraries/sessions.html

**Comment by quasiperfect** [comment]
Thanks for responding @avenirer 
I should read the user guide more carefully.
Is this true even is we use the database driver ?

**Comment by avenirer** [comment]
for sessions you can use the database, the files or whatever driver you choose to use.

**Comment by quasiperfect** [comment]
Thanks again @avenirer for all your help
